/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || "";

export const projectId =
  import.meta.env.VITE_SUPABASE_PROJECT_ID ||
  supabaseUrl.match(/^https:\/\/([^.]+)\.supabase\.co/)?.[1] ||
  "";

export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "";
